---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
<%
%w(
  ubuntu-12.04
  ubuntu-14.04
  centos-6.6
  centos-7.0
).each do |p|
%>
  - name: <%= p %>-chef-11
    driver:
      box: opscode-<%= p %>
    provisioner:
      require_chef_omnibus: 11

  - name: <%= p %>-chef-12
    driver:
      box: opscode-<%= p %>
    provisioner:
      require_chef_omnibus: 12
<% end %>

suites:
  - name: package
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: package
  - name: source
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: source
  - name: ppa
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: ppa
    excludes:
    <% %w( 11 12 ).each do |v| %>
      - centos-6.6-chef-<%= v %>
      - centos-7.0-chef-<%= v %>
    <% end %>
  - name: consul
    run_list:
      - recipe[my-consul-lb]
    excludes:
    <% %w( 11 12 ).each do |v| %>
      - ubuntu-12.04-chef-<%= v %>
      - ubuntu-14.04-chef-<%= v %>
      - centos-6.6-chef-<%= v %>
    <% end %>
