AllCops:
  Exclude:
    - Berksfile
    - metadata.rb
    - vendor/**/*
    - spec/**/*
    - test/**/*
Documentation:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
HashSyntax:
  EnforcedStyle: hash_rockets
